//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        public string Iban { get; set; }
        public string Currency_Fk { get; set; }
        public decimal Balance { get; set; }
        public string Username_Fk { get; set; }
        public System.DateTime DateOpened { get; set; }
        public string AccountType_Fk { get; set; }
        public long AccountNumber { get; set; }
        public Nullable<System.DateTime> DateExpired { get; set; }
        public string FriendlyName { get; set; }
        public Nullable<bool> Expired { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual User User { get; set; }
    }
}
